"""add P1 domain auth and reminder schema

Revision ID: ae17e2c0f9f8
Revises: 0001_p0_baseline
Create Date: 2026-07-18 19:15:31.420907
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ae17e2c0f9f8"
down_revision: str | None = "0001_p0_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    actor_type = postgresql.ENUM("user", "hermes", "system", "import", name="actor_type")
    subscription_status = postgresql.ENUM(
        "active",
        "trial",
        "pending_cancel",
        "paused",
        "cancelled",
        "expired",
        name="subscription_status",
    )
    event_type = postgresql.ENUM(
        "billing", "expiry", "trial_end", "cancellation_deadline", "contract_end", name="event_type"
    )
    event_status = postgresql.ENUM(
        "planned", "reconciled", "superseded", "cancelled", name="event_status"
    )
    delivery_status = postgresql.ENUM(
        "pending", "processing", "sent", "failed", "dead", "expired", name="delivery_status"
    )
    bind = op.get_bind()
    for enum_type in (actor_type, subscription_status, event_type, event_status, delivery_status):
        enum_type.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "actor_type",
            postgresql.ENUM(
                "user", "hermes", "system", "import", name="actor_type", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.String(length=200), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("scopes", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_api_tokens_token_hash")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "actor_type",
            postgresql.ENUM(
                "user", "hermes", "system", "import", name="actor_type", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.String(length=200), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("before_json", sa.JSON(), nullable=True),
        sa.Column("after_json", sa.JSON(), nullable=True),
        sa.Column("request_id", sa.String(length=100), nullable=False),
        sa.Column("idempotency_key_hash", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_occurred_at"), "audit_logs", ["occurred_at"], unique=False)
    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("normalized_name", sa.String(length=200), nullable=False),
        sa.Column("icon", sa.String(length=100), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("normalized_name", name=op.f("uq_categories_normalized_name")),
    )
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.String(length=200), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("path", sa.String(length=500), nullable=False),
        sa.Column("key_hash", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=128), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint("actor_id", "method", "path", "key_hash", name="uq_idempotency_scope"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("normalized_name", sa.String(length=200), nullable=False),
        sa.Column("color", sa.String(length=30), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("normalized_name", name=op.f("uq_tags_normalized_name")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("normalized_username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "password_changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("normalized_username", name=op.f("uq_users_normalized_username")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("csrf_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idle_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("vendor", sa.String(length=200), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "active",
                "trial",
                "pending_cancel",
                "paused",
                "cancelled",
                "expired",
                name="subscription_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("payment_method_description", sa.String(length=200), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_subscriptions_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
    )
    op.create_table(
        "billing_plans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("interval_unit", sa.String(length=10), nullable=False),
        sa.Column("interval_count", sa.Integer(), nullable=False),
        sa.Column("anchor_date", sa.Date(), nullable=False),
        sa.Column("next_billing_date", sa.Date(), nullable=True),
        sa.Column("auto_renew", sa.Boolean(), nullable=False),
        sa.Column("billing_mode", sa.String(length=20), nullable=False),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_billing_plans_subscription_id_subscriptions"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint("amount >= 0", name="ck_billing_plans_billing_plan_amount_nonnegative"),
        sa.CheckConstraint(
            "interval_count BETWEEN 1 AND 120",
            name="ck_billing_plans_billing_plan_interval_count_range",
        ),
        sa.CheckConstraint(
            "currency = upper(currency)", name="ck_billing_plans_billing_plan_currency_uppercase"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_billing_plans")),
    )
    op.create_index(
        op.f("ix_billing_plans_subscription_id"), "billing_plans", ["subscription_id"], unique=False
    )
    op.create_index(
        "uq_current_billing_plan",
        "billing_plans",
        ["subscription_id"],
        unique=True,
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.create_table(
        "reminder_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column(
            "event_type",
            postgresql.ENUM(
                "billing",
                "expiry",
                "trial_end",
                "cancellation_deadline",
                "contract_end",
                name="event_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("offset_days", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=50), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_reminder_rules_subscription_id_subscriptions"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            "offset_days BETWEEN 0 AND 3650", name="ck_reminder_rules_reminder_offset_range"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminder_rules")),
        sa.UniqueConstraint(
            "subscription_id", "event_type", "offset_days", "channel", name="uq_reminder_rule"
        ),
    )
    op.create_index(
        op.f("ix_reminder_rules_subscription_id"),
        "reminder_rules",
        ["subscription_id"],
        unique=False,
    )
    op.create_table(
        "service_dates",
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("trial_end_date", sa.Date(), nullable=True),
        sa.Column("service_expiry_date", sa.Date(), nullable=True),
        sa.Column("cancellation_deadline", sa.Date(), nullable=True),
        sa.Column("contract_end_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_service_dates_subscription_id_subscriptions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("subscription_id", name=op.f("pk_service_dates")),
    )
    op.create_table(
        "subscription_tags",
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_subscription_tags_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
            name=op.f("fk_subscription_tags_tag_id_tags"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("subscription_id", "tag_id", name=op.f("pk_subscription_tags")),
    )
    op.create_table(
        "billing_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("billing_plan_id", sa.UUID(), nullable=True),
        sa.Column(
            "event_type",
            postgresql.ENUM(
                "billing",
                "expiry",
                "trial_end",
                "cancellation_deadline",
                "contract_end",
                name="event_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "planned",
                "reconciled",
                "superseded",
                "cancelled",
                name="event_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["billing_plan_id"],
            ["billing_plans.id"],
            name=op.f("fk_billing_events_billing_plan_id_billing_plans"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_billing_events_subscription_id_subscriptions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_billing_events")),
        sa.UniqueConstraint(
            "billing_plan_id", "event_type", "event_date", name="uq_plan_event_date"
        ),
    )
    op.create_index(
        op.f("ix_billing_events_event_date"), "billing_events", ["event_date"], unique=False
    )
    op.create_index(
        op.f("ix_billing_events_subscription_id"),
        "billing_events",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        "uq_lifecycle_event_date",
        "billing_events",
        ["subscription_id", "event_type", "event_date"],
        unique=True,
        postgresql_where=sa.text("billing_plan_id IS NULL"),
    )
    op.create_table(
        "reminder_deliveries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("event_key", sa.String(length=500), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "processing",
                "sent",
                "failed",
                "dead",
                "expired",
                name="delivery_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["reminder_rules.id"],
            name=op.f("fk_reminder_deliveries_rule_id_reminder_rules"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name="ck_reminder_deliveries_delivery_attempt_count_nonnegative"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminder_deliveries")),
        sa.UniqueConstraint("event_key", name=op.f("uq_reminder_deliveries_event_key")),
    )
    op.create_index(
        op.f("ix_reminder_deliveries_rule_id"), "reminder_deliveries", ["rule_id"], unique=False
    )
    op.create_index(
        op.f("ix_reminder_deliveries_scheduled_for"),
        "reminder_deliveries",
        ["scheduled_for"],
        unique=False,
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("billing_event_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("external_ref", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["billing_event_id"],
            ["billing_events.id"],
            name=op.f("fk_payments_billing_event_id_billing_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_payments_subscription_id_subscriptions"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint("amount > 0", name="ck_payments_payment_amount_positive"),
        sa.CheckConstraint(
            "tax_amount >= 0 AND tax_amount <= amount", name="ck_payments_payment_tax_range"
        ),
        sa.CheckConstraint(
            "currency = upper(currency)", name="ck_payments_payment_currency_uppercase"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("source", "external_ref", name="uq_payment_external_ref"),
    )
    op.create_index(
        op.f("ix_payments_subscription_id"), "payments", ["subscription_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payments_subscription_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_reminder_deliveries_scheduled_for"), table_name="reminder_deliveries")
    op.drop_index(op.f("ix_reminder_deliveries_rule_id"), table_name="reminder_deliveries")
    op.drop_table("reminder_deliveries")
    op.drop_index("uq_lifecycle_event_date", table_name="billing_events")
    op.drop_index(op.f("ix_billing_events_subscription_id"), table_name="billing_events")
    op.drop_index(op.f("ix_billing_events_event_date"), table_name="billing_events")
    op.drop_table("billing_events")
    op.drop_table("subscription_tags")
    op.drop_table("service_dates")
    op.drop_index(op.f("ix_reminder_rules_subscription_id"), table_name="reminder_rules")
    op.drop_table("reminder_rules")
    op.drop_index("uq_current_billing_plan", table_name="billing_plans")
    op.drop_index(op.f("ix_billing_plans_subscription_id"), table_name="billing_plans")
    op.drop_table("billing_plans")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("users")
    op.drop_table("tags")
    op.drop_table("idempotency_records")
    op.drop_table("categories")
    op.drop_index(op.f("ix_audit_logs_occurred_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("api_tokens")
    bind = op.get_bind()
    for enum_name in (
        "delivery_status",
        "event_status",
        "event_type",
        "subscription_status",
        "actor_type",
    ):
        postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
